title: Lerning to crate a homepage with GitHub
theme: minima
author: J.B.G.P
description: I want to make a personal Website. That for is this one, createt by following the instructions of skills-github-pages
